[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_hello_world = "8iZz65rU8qKdEL9TmUgCkVJEpcWotiEU8315fw6NsdDN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
